name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: datasets_db 
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0'
        
    - name: Restore dependencies
      run: dotnet restore DataAnalyzeApi.sln
      
    - name: Build
      run: dotnet build DataAnalyzeApi.sln --no-restore --configuration Release
      
    - name: Run Unit Tests
      run: dotnet test DataAnalyzeApi.Unit/DataAnalyzeApi.Unit.csproj --configuration Release
      
    - name: Run Integration Tests
      run: dotnet test DataAnalyzeApi.Integration/DataAnalyzeApi.Integration.csproj --configuration Release
      env:
        # Postgres
        Postgres__Host: localhost
        Postgres__Username: testuser
        Postgres__Password: testpassword

        # Redis
        Redis__Host: localhost

        # JWT
        JwtConfig__Secret: ${{ secrets.JWTCONFIG_SECRET }}

        # Admin user
        Identity__AdminUser__Username: ${{ secrets.IDENTITY_ADMINUSER_USERNAME }}
        Identity__AdminUser__Email: ${{ secrets.IDENTITY_ADMINUSER_EMAIL }}
        Identity__AdminUser__FirstName: ${{ secrets.IDENTITY_ADMINUSER_FIRSTNAME }}
        Identity__AdminUser__LastName: ${{ secrets.IDENTITY_ADMINUSER_LASTNAME }}
        Identity__AdminUser__Password: ${{ secrets.IDENTITY_ADMINUSER_PASSWORD }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Build Docker image
      run: |
        docker build -f DataAnalyzeApi/Dockerfile -t data-analyze-api:latest DataAnalyzeApi
        docker save data-analyze-api:latest | gzip > data-analyze-api.tar.gz
        
    - name: Copy image to VM
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        source: "data-analyze-api.tar.gz"
        target: "/tmp/"
        
    - name: Deploy on VM
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          # Load the new image
          cd /tmp
          docker load < data-analyze-api.tar.gz
          rm data-analyze-api.tar.gz
          
          # Change to the directory with docker-compose
          cd /home/deploy/app
          
          # Stop and update the container
          docker-compose stop data-analyze-api
          docker-compose up -d data-analyze-api
          
          # Clean up old images
          docker image prune -f